language: php
php:
- 7.1
- 7.2
- 7.3
env:
- TYPO3_VERSION=^10.4 COVERAGE=0
matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: TYPO3_VERSION=^10.4 COVERAGE=0
    - php: 7.2
      env: TYPO3_VERSION=^10.4 COVERAGE=1
    - php: 7.1
      env: TYPO3_VERSION=^10.4 COVERAGE=0
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache"
before_install:
- |
  if [[ "$COVERAGE" == "0" ]]; then
    phpenv config-rm xdebug.ini
  fi;
- composer self-update
- composer --version
- if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com
  $GITHUB_COMPOSER_AUTH; fi
before_script:
- composer require typo3/minimal=$TYPO3_VERSION
- export TYPO3_PATH_WEB="$PWD/.Build/Web"
script:
- |
  echo; echo "Running unit tests";
  if [[ "$COVERAGE" == "1" ]]; then
    .Build/bin/phpunit -c Tests/UnitTests.xml --coverage-clover=.Build/unittest-coverage.clover
  else
    .Build/bin/phpunit -c Tests/UnitTests.xml
  fi;
- |
  echo; echo "Executing PHP mess detector"; .Build/bin/phpmd Classes/ text cleancode,codesize,controversial,design,naming || true
- |
  echo; echo "Executing PHP code sniffer"; .Build/bin/phpcs --runtime-set ignore_warnings_on_exit true --standard=PSR2 Classes/
after_script:
- |
  if [[ "$COVERAGE" == "1" ]]; then
    echo; echo "Uploading code coverage results";
    .Build/bin/ocular code-coverage:upload --format=php-clover .Build/unittest-coverage.clover
  fi
